stages:
- name: Pizza Server
  steps:
  - applyYamlConfig:
      path: ./manifests/app/pizza-server.yaml
  - applyYamlConfig:
      path: ./manifests/app/pizza-client.yaml
timeout: 60
notification: {}
