apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pizza-server
  name: pizza-server
  namespace: app-space
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: pizza-server
